#!/usr/bin/python
# -*- encoding:utf-8 -*-
import sys
import urllib2
import json
import pprint

args = sys.argv
reqs = json.loads(urllib2.urlopen("https://api.github.com/repos/{}/{}/pulls".format(args[1], args[2])).read())

for req in reqs:
    print u"{:>3} {:>20}  {:.54}".format(req["number"], req["user"]["login"], req["body"].replace('\n', ' ').replace('\r', ''))
